package com.ecnu.achieveit.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table activity
 */
public class Activity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_id
     *
     * @mbg.generated
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.primary_activity
     *
     * @mbg.generated
     */
    private String primaryActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.secondary_activity
     *
     * @mbg.generated
     */
    private String secondaryActivity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_id
     *
     * @return the value of activity.activity_id
     *
     * @mbg.generated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_id
     *
     * @param activityId the value for activity.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.primary_activity
     *
     * @return the value of activity.primary_activity
     *
     * @mbg.generated
     */
    public String getPrimaryActivity() {
        return primaryActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.primary_activity
     *
     * @param primaryActivity the value for activity.primary_activity
     *
     * @mbg.generated
     */
    public void setPrimaryActivity(String primaryActivity) {
        this.primaryActivity = primaryActivity == null ? null : primaryActivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.secondary_activity
     *
     * @return the value of activity.secondary_activity
     *
     * @mbg.generated
     */
    public String getSecondaryActivity() {
        return secondaryActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.secondary_activity
     *
     * @param secondaryActivity the value for activity.secondary_activity
     *
     * @mbg.generated
     */
    public void setSecondaryActivity(String secondaryActivity) {
        this.secondaryActivity = secondaryActivity == null ? null : secondaryActivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", activityId=").append(activityId);
        sb.append(", primaryActivity=").append(primaryActivity);
        sb.append(", secondaryActivity=").append(secondaryActivity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}