package com.ecnu.achieveit.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table client
 */
public class Client implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_id
     *
     * @mbg.generated
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.contacter
     *
     * @mbg.generated
     */
    private String contacter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_level
     *
     * @mbg.generated
     */
    private Integer clientLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_id
     *
     * @return the value of client.client_id
     *
     * @mbg.generated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_id
     *
     * @param clientId the value for client.client_id
     *
     * @mbg.generated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.contacter
     *
     * @return the value of client.contacter
     *
     * @mbg.generated
     */
    public String getContacter() {
        return contacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.contacter
     *
     * @param contacter the value for client.contacter
     *
     * @mbg.generated
     */
    public void setContacter(String contacter) {
        this.contacter = contacter == null ? null : contacter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.company_name
     *
     * @return the value of client.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.company_name
     *
     * @param companyName the value for client.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_level
     *
     * @return the value of client.client_level
     *
     * @mbg.generated
     */
    public Integer getClientLevel() {
        return clientLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_level
     *
     * @param clientLevel the value for client.client_level
     *
     * @mbg.generated
     */
    public void setClientLevel(Integer clientLevel) {
        this.clientLevel = clientLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.email
     *
     * @return the value of client.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.email
     *
     * @param email the value for client.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.telephone
     *
     * @return the value of client.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.telephone
     *
     * @param telephone the value for client.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.address
     *
     * @return the value of client.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.address
     *
     * @param address the value for client.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clientId=").append(clientId);
        sb.append(", contacter=").append(contacter);
        sb.append(", companyName=").append(companyName);
        sb.append(", clientLevel=").append(clientLevel);
        sb.append(", email=").append(email);
        sb.append(", telephone=").append(telephone);
        sb.append(", address=").append(address);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}