package com.ecnu.achieveit.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table employee
 */
@Getter
@Setter
@ToString
public class Employee implements Serializable {

    private String employeeId;

    private String employeeName;

    private String password;

    private String email;

    private String department;

    private String telephone;

    private String title;

    private static final long serialVersionUID = 1L;

}