package com.ecnu.achieveit.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project_risk
 */
public class ProjectRisk extends ProjectRiskKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_risk.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_risk.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_risk.risk_level
     *
     * @mbg.generated
     */
    private Integer riskLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_risk.influence
     *
     * @mbg.generated
     */
    private String influence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_risk.reactive_strategy
     *
     * @mbg.generated
     */
    private String reactiveStrategy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_risk.risk_state
     *
     * @mbg.generated
     */
    private String riskState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_risk.risk_owner_id
     *
     * @mbg.generated
     */
    private String riskOwnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_risk.risk_track_frequency
     *
     * @mbg.generated
     */
    private Long riskTrackFrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_risk
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_risk.type
     *
     * @return the value of project_risk.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_risk.type
     *
     * @param type the value for project_risk.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_risk.description
     *
     * @return the value of project_risk.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_risk.description
     *
     * @param description the value for project_risk.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_risk.risk_level
     *
     * @return the value of project_risk.risk_level
     *
     * @mbg.generated
     */
    public Integer getRiskLevel() {
        return riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_risk.risk_level
     *
     * @param riskLevel the value for project_risk.risk_level
     *
     * @mbg.generated
     */
    public void setRiskLevel(Integer riskLevel) {
        this.riskLevel = riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_risk.influence
     *
     * @return the value of project_risk.influence
     *
     * @mbg.generated
     */
    public String getInfluence() {
        return influence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_risk.influence
     *
     * @param influence the value for project_risk.influence
     *
     * @mbg.generated
     */
    public void setInfluence(String influence) {
        this.influence = influence == null ? null : influence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_risk.reactive_strategy
     *
     * @return the value of project_risk.reactive_strategy
     *
     * @mbg.generated
     */
    public String getReactiveStrategy() {
        return reactiveStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_risk.reactive_strategy
     *
     * @param reactiveStrategy the value for project_risk.reactive_strategy
     *
     * @mbg.generated
     */
    public void setReactiveStrategy(String reactiveStrategy) {
        this.reactiveStrategy = reactiveStrategy == null ? null : reactiveStrategy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_risk.risk_state
     *
     * @return the value of project_risk.risk_state
     *
     * @mbg.generated
     */
    public String getRiskState() {
        return riskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_risk.risk_state
     *
     * @param riskState the value for project_risk.risk_state
     *
     * @mbg.generated
     */
    public void setRiskState(String riskState) {
        this.riskState = riskState == null ? null : riskState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_risk.risk_owner_id
     *
     * @return the value of project_risk.risk_owner_id
     *
     * @mbg.generated
     */
    public String getRiskOwnerId() {
        return riskOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_risk.risk_owner_id
     *
     * @param riskOwnerId the value for project_risk.risk_owner_id
     *
     * @mbg.generated
     */
    public void setRiskOwnerId(String riskOwnerId) {
        this.riskOwnerId = riskOwnerId == null ? null : riskOwnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_risk.risk_track_frequency
     *
     * @return the value of project_risk.risk_track_frequency
     *
     * @mbg.generated
     */
    public Long getRiskTrackFrequency() {
        return riskTrackFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_risk.risk_track_frequency
     *
     * @param riskTrackFrequency the value for project_risk.risk_track_frequency
     *
     * @mbg.generated
     */
    public void setRiskTrackFrequency(Long riskTrackFrequency) {
        this.riskTrackFrequency = riskTrackFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", type=").append(type);
        sb.append(", description=").append(description);
        sb.append(", riskLevel=").append(riskLevel);
        sb.append(", influence=").append(influence);
        sb.append(", reactiveStrategy=").append(reactiveStrategy);
        sb.append(", riskState=").append(riskState);
        sb.append(", riskOwnerId=").append(riskOwnerId);
        sb.append(", riskTrackFrequency=").append(riskTrackFrequency);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}