package com.ecnu.achieveit.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project_risk
 */
public class ProjectRiskKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_risk.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_risk.risk_id
     *
     * @mbg.generated
     */
    private String riskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_risk
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_risk.project_id
     *
     * @return the value of project_risk.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_risk.project_id
     *
     * @param projectId the value for project_risk.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_risk.risk_id
     *
     * @return the value of project_risk.risk_id
     *
     * @mbg.generated
     */
    public String getRiskId() {
        return riskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_risk.risk_id
     *
     * @param riskId the value for project_risk.risk_id
     *
     * @mbg.generated
     */
    public void setRiskId(String riskId) {
        this.riskId = riskId == null ? null : riskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectId=").append(projectId);
        sb.append(", riskId=").append(riskId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}