package com.ecnu.achieveit.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project_member
 */
public class ProjectMember extends ProjectMemberKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member.boss_in_project_id
     *
     * @mbg.generated
     */
    private String bossInProjectId;

    /**
     * Database Column Remarks:
     *   可选择多个role，用；分割
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member.role
     *
     * @mbg.generated
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member.access_git
     *
     * @mbg.generated
     */
    private String accessGit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member.access_file_system
     *
     * @mbg.generated
     */
    private String accessFileSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member.in_email_list
     *
     * @mbg.generated
     */
    private Integer inEmailList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member.in_timesheet_module
     *
     * @mbg.generated
     */
    private Integer inTimesheetModule;

    /**
     * Database Column Remarks:
     *   pm、tl、dl：1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member.fault_track
     *
     * @mbg.generated
     */
    private Integer faultTrack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_member
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member.boss_in_project_id
     *
     * @return the value of project_member.boss_in_project_id
     *
     * @mbg.generated
     */
    public String getBossInProjectId() {
        return bossInProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member.boss_in_project_id
     *
     * @param bossInProjectId the value for project_member.boss_in_project_id
     *
     * @mbg.generated
     */
    public void setBossInProjectId(String bossInProjectId) {
        this.bossInProjectId = bossInProjectId == null ? null : bossInProjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member.role
     *
     * @return the value of project_member.role
     *
     * @mbg.generated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member.role
     *
     * @param role the value for project_member.role
     *
     * @mbg.generated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member.access_git
     *
     * @return the value of project_member.access_git
     *
     * @mbg.generated
     */
    public String getAccessGit() {
        return accessGit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member.access_git
     *
     * @param accessGit the value for project_member.access_git
     *
     * @mbg.generated
     */
    public void setAccessGit(String accessGit) {
        this.accessGit = accessGit == null ? null : accessGit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member.access_file_system
     *
     * @return the value of project_member.access_file_system
     *
     * @mbg.generated
     */
    public String getAccessFileSystem() {
        return accessFileSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member.access_file_system
     *
     * @param accessFileSystem the value for project_member.access_file_system
     *
     * @mbg.generated
     */
    public void setAccessFileSystem(String accessFileSystem) {
        this.accessFileSystem = accessFileSystem == null ? null : accessFileSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member.in_email_list
     *
     * @return the value of project_member.in_email_list
     *
     * @mbg.generated
     */
    public Integer getInEmailList() {
        return inEmailList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member.in_email_list
     *
     * @param inEmailList the value for project_member.in_email_list
     *
     * @mbg.generated
     */
    public void setInEmailList(Integer inEmailList) {
        this.inEmailList = inEmailList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member.in_timesheet_module
     *
     * @return the value of project_member.in_timesheet_module
     *
     * @mbg.generated
     */
    public Integer getInTimesheetModule() {
        return inTimesheetModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member.in_timesheet_module
     *
     * @param inTimesheetModule the value for project_member.in_timesheet_module
     *
     * @mbg.generated
     */
    public void setInTimesheetModule(Integer inTimesheetModule) {
        this.inTimesheetModule = inTimesheetModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member.fault_track
     *
     * @return the value of project_member.fault_track
     *
     * @mbg.generated
     */
    public Integer getFaultTrack() {
        return faultTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member.fault_track
     *
     * @param faultTrack the value for project_member.fault_track
     *
     * @mbg.generated
     */
    public void setFaultTrack(Integer faultTrack) {
        this.faultTrack = faultTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_member
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bossInProjectId=").append(bossInProjectId);
        sb.append(", role=").append(role);
        sb.append(", accessGit=").append(accessGit);
        sb.append(", accessFileSystem=").append(accessFileSystem);
        sb.append(", inEmailList=").append(inEmailList);
        sb.append(", inTimesheetModule=").append(inTimesheetModule);
        sb.append(", faultTrack=").append(faultTrack);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}