package com.ecnu.achieveit.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project_device
 */
public class ProjectDevice extends ProjectDeviceKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_device.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   0：未归还，1：已归还
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_device.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_device.device_manager_id
     *
     * @mbg.generated
     */
    private String deviceManagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_device.checkin_date
     *
     * @mbg.generated
     */
    private Date checkinDate;

    /**
     * Database Column Remarks:
     *   以月为单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_device.total_use_time
     *
     * @mbg.generated
     */
    private Integer totalUseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_device.last_verify_date
     *
     * @mbg.generated
     */
    private Date lastVerifyDate;

    /**
     * Database Column Remarks:
     *   当state为1时使用该变量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_device.return_date
     *
     * @mbg.generated
     */
    private Date returnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_device
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_device.type
     *
     * @return the value of project_device.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_device.type
     *
     * @param type the value for project_device.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_device.state
     *
     * @return the value of project_device.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_device.state
     *
     * @param state the value for project_device.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_device.device_manager_id
     *
     * @return the value of project_device.device_manager_id
     *
     * @mbg.generated
     */
    public String getDeviceManagerId() {
        return deviceManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_device.device_manager_id
     *
     * @param deviceManagerId the value for project_device.device_manager_id
     *
     * @mbg.generated
     */
    public void setDeviceManagerId(String deviceManagerId) {
        this.deviceManagerId = deviceManagerId == null ? null : deviceManagerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_device.checkin_date
     *
     * @return the value of project_device.checkin_date
     *
     * @mbg.generated
     */
    public Date getCheckinDate() {
        return checkinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_device.checkin_date
     *
     * @param checkinDate the value for project_device.checkin_date
     *
     * @mbg.generated
     */
    public void setCheckinDate(Date checkinDate) {
        this.checkinDate = checkinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_device.total_use_time
     *
     * @return the value of project_device.total_use_time
     *
     * @mbg.generated
     */
    public Integer getTotalUseTime() {
        return totalUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_device.total_use_time
     *
     * @param totalUseTime the value for project_device.total_use_time
     *
     * @mbg.generated
     */
    public void setTotalUseTime(Integer totalUseTime) {
        this.totalUseTime = totalUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_device.last_verify_date
     *
     * @return the value of project_device.last_verify_date
     *
     * @mbg.generated
     */
    public Date getLastVerifyDate() {
        return lastVerifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_device.last_verify_date
     *
     * @param lastVerifyDate the value for project_device.last_verify_date
     *
     * @mbg.generated
     */
    public void setLastVerifyDate(Date lastVerifyDate) {
        this.lastVerifyDate = lastVerifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_device.return_date
     *
     * @return the value of project_device.return_date
     *
     * @mbg.generated
     */
    public Date getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_device.return_date
     *
     * @param returnDate the value for project_device.return_date
     *
     * @mbg.generated
     */
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_device
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", type=").append(type);
        sb.append(", state=").append(state);
        sb.append(", deviceManagerId=").append(deviceManagerId);
        sb.append(", checkinDate=").append(checkinDate);
        sb.append(", totalUseTime=").append(totalUseTime);
        sb.append(", lastVerifyDate=").append(lastVerifyDate);
        sb.append(", returnDate=").append(returnDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}