package com.ecnu.achieveit.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project_basic_info
 */
public class ProjectBasicInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.client_id
     *
     * @mbg.generated
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.exp_start_date
     *
     * @mbg.generated
     */
    private Date expStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.exp_end_date
     *
     * @mbg.generated
     */
    private Date expEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.project_boss_id
     *
     * @mbg.generated
     */
    private String projectBossId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.milestone
     *
     * @mbg.generated
     */
    private String milestone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.technology
     *
     * @mbg.generated
     */
    private String technology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.business_domain
     *
     * @mbg.generated
     */
    private String businessDomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.main_functions
     *
     * @mbg.generated
     */
    private String mainFunctions;

    /**
     * Database Column Remarks:
     *   this is a url.
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.output_link
     *
     * @mbg.generated
     */
    private String outputLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.git_address
     *
     * @mbg.generated
     */
    private String gitAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_basic_info.file_system_address
     *
     * @mbg.generated
     */
    private String fileSystemAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.project_id
     *
     * @return the value of project_basic_info.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.project_id
     *
     * @param projectId the value for project_basic_info.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.project_name
     *
     * @return the value of project_basic_info.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.project_name
     *
     * @param projectName the value for project_basic_info.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.client_id
     *
     * @return the value of project_basic_info.client_id
     *
     * @mbg.generated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.client_id
     *
     * @param clientId the value for project_basic_info.client_id
     *
     * @mbg.generated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.state
     *
     * @return the value of project_basic_info.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.state
     *
     * @param state the value for project_basic_info.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.exp_start_date
     *
     * @return the value of project_basic_info.exp_start_date
     *
     * @mbg.generated
     */
    public Date getExpStartDate() {
        return expStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.exp_start_date
     *
     * @param expStartDate the value for project_basic_info.exp_start_date
     *
     * @mbg.generated
     */
    public void setExpStartDate(Date expStartDate) {
        this.expStartDate = expStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.exp_end_date
     *
     * @return the value of project_basic_info.exp_end_date
     *
     * @mbg.generated
     */
    public Date getExpEndDate() {
        return expEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.exp_end_date
     *
     * @param expEndDate the value for project_basic_info.exp_end_date
     *
     * @mbg.generated
     */
    public void setExpEndDate(Date expEndDate) {
        this.expEndDate = expEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.project_boss_id
     *
     * @return the value of project_basic_info.project_boss_id
     *
     * @mbg.generated
     */
    public String getProjectBossId() {
        return projectBossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.project_boss_id
     *
     * @param projectBossId the value for project_basic_info.project_boss_id
     *
     * @mbg.generated
     */
    public void setProjectBossId(String projectBossId) {
        this.projectBossId = projectBossId == null ? null : projectBossId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.milestone
     *
     * @return the value of project_basic_info.milestone
     *
     * @mbg.generated
     */
    public String getMilestone() {
        return milestone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.milestone
     *
     * @param milestone the value for project_basic_info.milestone
     *
     * @mbg.generated
     */
    public void setMilestone(String milestone) {
        this.milestone = milestone == null ? null : milestone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.technology
     *
     * @return the value of project_basic_info.technology
     *
     * @mbg.generated
     */
    public String getTechnology() {
        return technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.technology
     *
     * @param technology the value for project_basic_info.technology
     *
     * @mbg.generated
     */
    public void setTechnology(String technology) {
        this.technology = technology == null ? null : technology.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.business_domain
     *
     * @return the value of project_basic_info.business_domain
     *
     * @mbg.generated
     */
    public String getBusinessDomain() {
        return businessDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.business_domain
     *
     * @param businessDomain the value for project_basic_info.business_domain
     *
     * @mbg.generated
     */
    public void setBusinessDomain(String businessDomain) {
        this.businessDomain = businessDomain == null ? null : businessDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.main_functions
     *
     * @return the value of project_basic_info.main_functions
     *
     * @mbg.generated
     */
    public String getMainFunctions() {
        return mainFunctions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.main_functions
     *
     * @param mainFunctions the value for project_basic_info.main_functions
     *
     * @mbg.generated
     */
    public void setMainFunctions(String mainFunctions) {
        this.mainFunctions = mainFunctions == null ? null : mainFunctions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.output_link
     *
     * @return the value of project_basic_info.output_link
     *
     * @mbg.generated
     */
    public String getOutputLink() {
        return outputLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.output_link
     *
     * @param outputLink the value for project_basic_info.output_link
     *
     * @mbg.generated
     */
    public void setOutputLink(String outputLink) {
        this.outputLink = outputLink == null ? null : outputLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.git_address
     *
     * @return the value of project_basic_info.git_address
     *
     * @mbg.generated
     */
    public String getGitAddress() {
        return gitAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.git_address
     *
     * @param gitAddress the value for project_basic_info.git_address
     *
     * @mbg.generated
     */
    public void setGitAddress(String gitAddress) {
        this.gitAddress = gitAddress == null ? null : gitAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_basic_info.file_system_address
     *
     * @return the value of project_basic_info.file_system_address
     *
     * @mbg.generated
     */
    public String getFileSystemAddress() {
        return fileSystemAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_basic_info.file_system_address
     *
     * @param fileSystemAddress the value for project_basic_info.file_system_address
     *
     * @mbg.generated
     */
    public void setFileSystemAddress(String fileSystemAddress) {
        this.fileSystemAddress = fileSystemAddress == null ? null : fileSystemAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectId=").append(projectId);
        sb.append(", projectName=").append(projectName);
        sb.append(", clientId=").append(clientId);
        sb.append(", state=").append(state);
        sb.append(", expStartDate=").append(expStartDate);
        sb.append(", expEndDate=").append(expEndDate);
        sb.append(", projectBossId=").append(projectBossId);
        sb.append(", milestone=").append(milestone);
        sb.append(", technology=").append(technology);
        sb.append(", businessDomain=").append(businessDomain);
        sb.append(", mainFunctions=").append(mainFunctions);
        sb.append(", outputLink=").append(outputLink);
        sb.append(", gitAddress=").append(gitAddress);
        sb.append(", fileSystemAddress=").append(fileSystemAddress);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}