package com.ecnu.achieveit.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project_function
 */
public class ProjectFunctionKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_function.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_function.primary_function
     *
     * @mbg.generated
     */
    private String primaryFunction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_function.secondary_function
     *
     * @mbg.generated
     */
    private String secondaryFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_function
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_function.project_id
     *
     * @return the value of project_function.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_function.project_id
     *
     * @param projectId the value for project_function.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_function.primary_function
     *
     * @return the value of project_function.primary_function
     *
     * @mbg.generated
     */
    public String getPrimaryFunction() {
        return primaryFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_function.primary_function
     *
     * @param primaryFunction the value for project_function.primary_function
     *
     * @mbg.generated
     */
    public void setPrimaryFunction(String primaryFunction) {
        this.primaryFunction = primaryFunction == null ? null : primaryFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_function.secondary_function
     *
     * @return the value of project_function.secondary_function
     *
     * @mbg.generated
     */
    public String getSecondaryFunction() {
        return secondaryFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_function.secondary_function
     *
     * @param secondaryFunction the value for project_function.secondary_function
     *
     * @mbg.generated
     */
    public void setSecondaryFunction(String secondaryFunction) {
        this.secondaryFunction = secondaryFunction == null ? null : secondaryFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_function
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectId=").append(projectId);
        sb.append(", primaryFunction=").append(primaryFunction);
        sb.append(", secondaryFunction=").append(secondaryFunction);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}