package com.ecnu.achieveit.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table review_defect_info
 */
public class ReviewDefectInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_defect_info.review_defect_id
     *
     * @mbg.generated
     */
    private Integer reviewDefectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_defect_info.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     * Database Column Remarks:
     *   review, defect
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_defect_info.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_defect_info.provider_id
     *
     * @mbg.generated
     */
    private String providerId;

    /**
     * Database Column Remarks:
     *   0: 未处理 1: 已处理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_defect_info.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_defect_info.solver_id
     *
     * @mbg.generated
     */
    private String solverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_defect_info.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_defect_info.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_defect_info.link
     *
     * @mbg.generated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_defect_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_defect_info.review_defect_id
     *
     * @return the value of review_defect_info.review_defect_id
     *
     * @mbg.generated
     */
    public Integer getReviewDefectId() {
        return reviewDefectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_defect_info.review_defect_id
     *
     * @param reviewDefectId the value for review_defect_info.review_defect_id
     *
     * @mbg.generated
     */
    public void setReviewDefectId(Integer reviewDefectId) {
        this.reviewDefectId = reviewDefectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_defect_info.project_id
     *
     * @return the value of review_defect_info.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_defect_info.project_id
     *
     * @param projectId the value for review_defect_info.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_defect_info.type
     *
     * @return the value of review_defect_info.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_defect_info.type
     *
     * @param type the value for review_defect_info.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_defect_info.provider_id
     *
     * @return the value of review_defect_info.provider_id
     *
     * @mbg.generated
     */
    public String getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_defect_info.provider_id
     *
     * @param providerId the value for review_defect_info.provider_id
     *
     * @mbg.generated
     */
    public void setProviderId(String providerId) {
        this.providerId = providerId == null ? null : providerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_defect_info.state
     *
     * @return the value of review_defect_info.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_defect_info.state
     *
     * @param state the value for review_defect_info.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_defect_info.solver_id
     *
     * @return the value of review_defect_info.solver_id
     *
     * @mbg.generated
     */
    public String getSolverId() {
        return solverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_defect_info.solver_id
     *
     * @param solverId the value for review_defect_info.solver_id
     *
     * @mbg.generated
     */
    public void setSolverId(String solverId) {
        this.solverId = solverId == null ? null : solverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_defect_info.description
     *
     * @return the value of review_defect_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_defect_info.description
     *
     * @param description the value for review_defect_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_defect_info.date
     *
     * @return the value of review_defect_info.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_defect_info.date
     *
     * @param date the value for review_defect_info.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_defect_info.link
     *
     * @return the value of review_defect_info.link
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_defect_info.link
     *
     * @param link the value for review_defect_info.link
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_defect_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reviewDefectId=").append(reviewDefectId);
        sb.append(", projectId=").append(projectId);
        sb.append(", type=").append(type);
        sb.append(", providerId=").append(providerId);
        sb.append(", state=").append(state);
        sb.append(", solverId=").append(solverId);
        sb.append(", description=").append(description);
        sb.append(", date=").append(date);
        sb.append(", link=").append(link);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}