package com.ecnu.achieveit.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table timesheet
 */
public class Timesheet implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.timesheet_id
     *
     * @mbg.generated
     */
    private Integer timesheetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.employee_id
     *
     * @mbg.generated
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.primary_function
     *
     * @mbg.generated
     */
    private String primaryFunction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.secondary_funtion
     *
     * @mbg.generated
     */
    private String secondaryFuntion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.primary_activity
     *
     * @mbg.generated
     */
    private String primaryActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.secondary_activity
     *
     * @mbg.generated
     */
    private String secondaryActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * Database Column Remarks:
     *   草稿、已提交、已确认、打回
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timesheet.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table timesheet
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.timesheet_id
     *
     * @return the value of timesheet.timesheet_id
     *
     * @mbg.generated
     */
    public Integer getTimesheetId() {
        return timesheetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.timesheet_id
     *
     * @param timesheetId the value for timesheet.timesheet_id
     *
     * @mbg.generated
     */
    public void setTimesheetId(Integer timesheetId) {
        this.timesheetId = timesheetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.project_id
     *
     * @return the value of timesheet.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.project_id
     *
     * @param projectId the value for timesheet.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.employee_id
     *
     * @return the value of timesheet.employee_id
     *
     * @mbg.generated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.employee_id
     *
     * @param employeeId the value for timesheet.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.primary_function
     *
     * @return the value of timesheet.primary_function
     *
     * @mbg.generated
     */
    public String getPrimaryFunction() {
        return primaryFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.primary_function
     *
     * @param primaryFunction the value for timesheet.primary_function
     *
     * @mbg.generated
     */
    public void setPrimaryFunction(String primaryFunction) {
        this.primaryFunction = primaryFunction == null ? null : primaryFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.secondary_funtion
     *
     * @return the value of timesheet.secondary_funtion
     *
     * @mbg.generated
     */
    public String getSecondaryFuntion() {
        return secondaryFuntion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.secondary_funtion
     *
     * @param secondaryFuntion the value for timesheet.secondary_funtion
     *
     * @mbg.generated
     */
    public void setSecondaryFuntion(String secondaryFuntion) {
        this.secondaryFuntion = secondaryFuntion == null ? null : secondaryFuntion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.primary_activity
     *
     * @return the value of timesheet.primary_activity
     *
     * @mbg.generated
     */
    public String getPrimaryActivity() {
        return primaryActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.primary_activity
     *
     * @param primaryActivity the value for timesheet.primary_activity
     *
     * @mbg.generated
     */
    public void setPrimaryActivity(String primaryActivity) {
        this.primaryActivity = primaryActivity == null ? null : primaryActivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.secondary_activity
     *
     * @return the value of timesheet.secondary_activity
     *
     * @mbg.generated
     */
    public String getSecondaryActivity() {
        return secondaryActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.secondary_activity
     *
     * @param secondaryActivity the value for timesheet.secondary_activity
     *
     * @mbg.generated
     */
    public void setSecondaryActivity(String secondaryActivity) {
        this.secondaryActivity = secondaryActivity == null ? null : secondaryActivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.date
     *
     * @return the value of timesheet.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.date
     *
     * @param date the value for timesheet.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.start_time
     *
     * @return the value of timesheet.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.start_time
     *
     * @param startTime the value for timesheet.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.end_time
     *
     * @return the value of timesheet.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.end_time
     *
     * @param endTime the value for timesheet.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timesheet.state
     *
     * @return the value of timesheet.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timesheet.state
     *
     * @param state the value for timesheet.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", timesheetId=").append(timesheetId);
        sb.append(", projectId=").append(projectId);
        sb.append(", employeeId=").append(employeeId);
        sb.append(", primaryFunction=").append(primaryFunction);
        sb.append(", secondaryFuntion=").append(secondaryFuntion);
        sb.append(", primaryActivity=").append(primaryActivity);
        sb.append(", secondaryActivity=").append(secondaryActivity);
        sb.append(", date=").append(date);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}