package com.ecnu.achieveit.dao;

import com.ecnu.achieveit.model.Employee;
import org.apache.ibatis.annotations.Mapper;
import sun.management.snmp.jvmmib.EnumJvmMemPoolCollectThreshdSupport;

import java.util.List;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    Employee selectByPrimaryKey(String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Employee record);

    List<Employee> selectEmployeeList();

    List<Employee> selectBasicEmployeeList();

    Employee selectBasicByPrimaryKey(String employeeId);

    Employee selectBasicByEmail(String email);

    Employee selectByEmail(String email);

    List<Employee> selectBasicEmployeeListByTitleId(String titleId);
}