package com.ecnu.achieveit.dao;

import com.ecnu.achieveit.model.ProjectFunctionKey;

import java.util.List;

public interface ProjectFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ProjectFunctionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_function
     *
     * @mbg.generated
     */
    int insert(ProjectFunctionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_function
     *
     * @mbg.generated
     */
    int insertSelective(ProjectFunctionKey record);

    List<String> selectPrimaryFunction();

    List<String> selectSecondaryFunctionByPrimaryFunction(String primaryFunction);
}