package com.ecnu.achieveit.dao;

import com.ecnu.achieveit.model.ProjectRisk;
import com.ecnu.achieveit.model.ProjectRiskKey;
import com.ecnu.achieveit.modelview.RiskTrackEmail;

import java.util.List;

public interface ProjectRiskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ProjectRiskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk
     *
     * @mbg.generated
     */
    int insert(ProjectRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk
     *
     * @mbg.generated
     */
    int insertSelective(ProjectRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk
     *
     * @mbg.generated
     */
    ProjectRisk selectByPrimaryKey(ProjectRiskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectRisk record);

    List<ProjectRisk> selectByProjectId(String projectId);

    List<ProjectRisk> selectByOwnerId(String ownerId);

    List<ProjectRisk> selectByRelatedId(String relatedId);

    List<RiskTrackEmail> selectProjectListWithManager();

}