package com.ecnu.achieveit.dao;

import com.ecnu.achieveit.model.ProjectMember;
import com.ecnu.achieveit.model.ProjectMemberKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.PathVariable;

import java.util.List;

public interface ProjectMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ProjectMemberKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_member
     *
     * @mbg.generated
     */
    int insert(ProjectMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_member
     *
     * @mbg.generated
     */
    int insertSelective(ProjectMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_member
     *
     * @mbg.generated
     */
    ProjectMember selectByPrimaryKey(ProjectMemberKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectMember record);


    List<ProjectMember> selectListByProjectId(String projectId);

    List<ProjectMember> selectListByRole(@Param("projectId") String projectId, @Param("role") String role);

    List<String> selectProjectIdByEmployeeId(String employeeId);
}