package com.ecnu.achieveit.dao;

import com.ecnu.achieveit.model.ProjectBasicInfo;

public interface ProjectBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    int insert(ProjectBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    int insertSelective(ProjectBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    ProjectBasicInfo selectByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectBasicInfo record);
}