package com.ecnu.achieveit.dao;

import com.ecnu.achieveit.model.ProjectBasicInfo;
import com.ecnu.achieveit.model.ProjectId;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    int insert(ProjectBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    int insertSelective(ProjectBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    ProjectBasicInfo selectByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectBasicInfo record);

    /**
     *
     * @param employeeId
     * @return List<ProjectBasicInfo>
     */
     List<ProjectBasicInfo> selectByEmployeeId(String employeeId);

    /**
     *
     * @param clientId
     * @return List<ProjectBasicInfo>
     */
     List<ProjectBasicInfo> selectByClientId(String clientId);

    /**
     *
     * @param state
     * @return List<ProjectBasicInfo>
     */
     List<ProjectBasicInfo> selectByState(String state);

    /**
     *
     * @param bossId
     * @return List<ProjectBasicInfo>
     */
     List<ProjectBasicInfo> selectByBossId(String bossId);

    /**
     *
     * @param keyWord
     * @return List<ProjectBasicInfo>
     */
     List<ProjectBasicInfo> selectByKeyWord(@Param("keyWord") String keyWord,
                                            @Param("employeeId") String employeeId);

     int updateStateById(@Param("projectId") String projectId,
                         @Param("state") String state);

     int updateOutputLinkOfProjectInfo(@Param("projectId")String projectId,
                                       @Param("outputLink")String outputLink);
}