package com.ecnu.achieveit.dao;

import com.ecnu.achieveit.model.ReviewDefectInfo;

public interface ReviewDefectInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_defect_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer reviewDefectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_defect_info
     *
     * @mbg.generated
     */
    int insert(ReviewDefectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_defect_info
     *
     * @mbg.generated
     */
    int insertSelective(ReviewDefectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_defect_info
     *
     * @mbg.generated
     */
    ReviewDefectInfo selectByPrimaryKey(Integer reviewDefectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_defect_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReviewDefectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_defect_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReviewDefectInfo record);
}