package com.ecnu.achieveit.dao;

import com.ecnu.achieveit.model.Timesheet;

public interface TimesheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer timesheetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated
     */
    int insert(Timesheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated
     */
    int insertSelective(Timesheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated
     */
    Timesheet selectByPrimaryKey(Integer timesheetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Timesheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Timesheet record);
}